pipeline {
    agent {
      label 'master'
    }
    environment {
         harbor_url = "harbor.seassoon.com.cn"
         def mvnHome = tool 'M3'
         PATH = "${mvnHome}/bin:${PATH}"
    }
    stages {


        stage('Clone Code') {
            steps {

                git branch: 'develop',credentialsId: '7c6bf629-e317-4594-95d0-af843fbb9224', url: 'http://gitlab.seassoon.ai/sixiang/sixiang-2.0/sixiang-frontend.git'
                echo "1.Git Clone Code #{VERSION}"

            }
        }
        stage('Maven Build') {
            steps {

                echo "2.Maven Build Stage"
                sh 'npm run build'
            }
        }
        stage('Image Build') {

            steps {
            echo "3.Image Build Stage"
            sh 'ls;'
            sh 'docker build -f Dockerfile  -t sixiang-dev-frontend:latest . '
            withCredentials([usernamePassword(credentialsId: 'harbor', passwordVariable: 'password', usernameVariable: 'username')]){
                    sh 'docker login -u ${username} -p ${password} ${harbor_url}'
                    sh 'docker tag  sixiang-dev:latest ${harbor_url}/sixiang/sixiang-dev-frontend:latest'
            }
            }
        }
        stage('Push') {
            // agent {
            //     label 'master'
            // }
            steps {
            echo "4.Push Docker Image Stage"
            withCredentials([usernamePassword(credentialsId: 'harbor', passwordVariable: 'password', usernameVariable: 'username')]){
                    sh 'docker login -u ${username} -p ${password} ${harbor_url}'
                    sh "pwd;docker push ${harbor_url}/sixiang/sixiang-dev-frontend:latest"
                }
            }
        }
        //  stage('YAML') {
        //     steps {
        //      echo "6. Change YAML File Stage"
        //       sh 'sed -i "s#XXX#${harbor_url}/sixiang/sixiang-dev:latest#g" sixiang_dev_k8s_api_online.yaml'
        //       sh 'cat sixiang_dev_k8s_api_online.yaml'
        //     }
        //  }
        //   stage('Deploy') {

        //       steps {
        //        echo "7. Deploy To K8s Stage"

        //       withKubeConfig(credentialsId: 'k8s-dev',namespace: 'sixiang-dev') {
        //            sh 'kubectl get pods -n sixiang-dev'
        //            sh 'kubectl apply -f k8s_permission_secret_online.yaml -n sixiang-dev'
        //            sh 'kubectl apply -f sixiang_dev_k8s_api_online.yaml -n sixiang-dev'
        //      }



        //   }
    //    }

    }
}
